theme: jekyll-theme-slate
title: Welcome to Shubham K's Homepage on GitHub. 
description: I am currently coding for machine learning models. Suggestions for projects and pages for me to follow will be appreciated. 
